spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-mcms-open?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: rootroot
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource